### ISSUE TITLE
Set camera defaults

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/opencast-camera-control#54]
It would be helpful to set some default values for cameras instead of setting the same value over and over again.
This could look like this:

```yml
camera:
  __default:
    - type: panasonic
      user: camerauser
      password: secret
```
